# Configuration to find a build languages libraries for loading

[languages.rust]
language_library_name = "rust"
library_location = "libtree-sitter-rust.so"
file_extensions = [ "rs", "ltlsp" ]
expressions = [ "(line_comment) @line", "(block_comment) @block" ]
