# Configuration to find a build languages libraries for loading

[languages.rust]
language_name = "rust"
language_fn_name = "tree_sitter_rust"
language_library_name = "libtree-sitter-rust"
file_extensions = [ "rs" ]
expressions = [ "(line_comment) @line", "(block_comment) @block", "(string_content) @content" ]

[languages.ltlsp]
language_name = "ltlsp"
language_fn_name = "tree_sitter_rust"
language_library_name = "libtree-sitter-rust"
file_extensions = [ "ltlsp" ]
expressions = [ "(line_comment) @line", "(block_comment) @block", "(string_content) @content" ]

[languages.c-sharp]
language_name = "c-sharp"
language_fn_name = "tree_sitter_c_sharp"
language_library_name = "libtree-sitter-c_sharp"
file_extensions = [ "cs" ]
expressions = [ "(comment) @comment" ]

[languages.go]
language_name = "go"
language_fn_name = "tree_sitter_go"
language_library_name = "libtree-sitter-go"
file_extensions = [ "go" ]
expressions = [ "(comment) @comment" ]

[languages.git-commit]
language_name = "git-commit"
language_fn_name = "tree_sitter_git_commit"
language_library_name = "libtree-sitter-git_commit"
file_extensions = [ "COMMIT_EDITMSG" ]
expressions = [ "(subject) @subject", "(message) @message" ]
