# Configuration to find a builid languages libraries for loading

[language.rust]
library_location = "libtree-sitter-rust.so"
file_extensions = [ "rs", "ltlsp" ]
expresson = [ "(line_comment) @line", "(block_comment) @block" ]
